name: Update Local Proxy Certificates
on:
  workflow_dispatch: ~
  schedule:
    - cron: "0 0 */45 * *"
jobs:
  updateCerts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Generate Certificate
        run: |
          curl -L -o lego.tar.gz https://github.com/go-acme/lego/releases/download/v4.7.0/lego_v4.7.0_linux_amd64.tar.gz
          tar -xvzf lego.tar.gz && chmod +x lego
          CLOUDFLARE_DNS_API_TOKEN=${{ secrets.CLOUDFLARE_DNS_API_TOKEN_ACMACALISTER_DEV }} \
          ./lego -s https://acme-staging-v02.api.letsencrypt.org/directory --email acmacalister@gmail.com --dns cloudflare --domains '*.acmacalister.dev' --path .lego -a --dns.resolvers 1.1.1.1:53 run
      - name: Update Certificate Files
        run: |
          cp .lego/certificates/_.acmacalister.dev.key app/key.pem
          cp .lego/certificates/_.acmacalister.dev.crt app/cert.pem
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: update proxy certificate
          title: Update proxy certificate
          body: Update the proxy cert with new LE cert
          branch: update-proxy-cert
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          delete-branch: true
          add-paths: |
            app/key.pem
            app/cert.pem